- name: Deploy Node.js App Behind Nginx with Docker and Ansible on Amazon Linux 2
  hosts: ec2
  become: yes

  tasks:
    - name: Update the package manager (using dnf for Amazon Linux 2)
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install required packages for Docker
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Install Docker from the official Docker repository
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: add ec2-user to docker group
      user:
            name: ec2-user
            group: docker
            append: yes

    - name: install docker-compose 
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: +x'

    - name: Copy Dockerfile
      copy:
        src: files/Dockerfile
        dest: /home/ec2-user

    - name: Copy nginx.conf
      copy:
        src: files/nginx.conf
        dest: /home/ec2-user

    - name: Copy docker-compose.yml
      copy:
        src: files/docker-compose.yaml
        dest: /home/ec2-user

    - name: Start the application with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user
